version: "3.8"

services:
    app:
        image: johnkristan/expensepro:latest
        restart: always
        ports:
            - "8000:9000"
        env_file:
            - .env
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf:ro
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
